language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - sudo: required

env:
  matrix:
    - RELEASE=trusty VERSION=2.7.8
    - RELEASE=trusty VERSION=2.7.9
    - RELEASE=trusty VERSION=2.7.10
    - RELEASE=precise VERSION=2.7.8
    - RELEASE=precise VERSION=2.7.9
    - RELEASE=precise VERSION=2.7.10

install:
  - pushd /opt/pyenv/
  - sudo git checkout master
  - sudo git pull
  - popd

before_script:
  - 'export INSTALL_DEST=${INSTALL_DEST:-/opt/python}'
  - 'export LSB_RELEASE=${LSB_RELEASE:-$(lsb_release -rs || echo ${$(sw_vers -productVersion)%*.*})}'
  - 'export OS_NAME=${OS_NAME:-$(lsb_release -is | tr "A-Z" "a-z" || "osx")}'
  - 'export ARCH=${ARCH:-$(uname -m)}'
  - 'export PACKAGES=${PACKAGES:-pip numpy nose pytest mock wheel}'

script: ./build-python

after_success: ./create-archive

after_failure:
  - cat /tmp/python-build.*.log

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
