#!/usr/bin/env bash

set -o errexit

if [[ ! $INSTALL_DEST ]] ; then
  echo 'Missing INSTALL_DEST'
  exit 1
fi

if [[ ! $VERSION ]] ; then
  echo 'Missing $VERSION'
  exit 1
fi

set -o xtrace

sudo env PYTHON_BUILD_ROOT=/opt/pyenv/plugins/python-build \
  /opt/pyenv/plugins/python-build/bin/python-build $VERSION $INSTALL_DEST/$VERSION

if [[ $ALIAS ]] ; then
  sudo ln -s $INSTALL_DEST/$VERSION $INSTALL_DEST/$ALIAS
fi

virtualenv --distribute --python=$INSTALL_DEST/$VERSION/bin/python \
  /home/travis/virtualenv/python$VERSION

$INSTALL_DEST/$VERSION/bin/python -c "import sys; opts = {1114111: 'ucs4', 65535: 'ucs2'}; print(opts.get(sys.maxunicode));"

if [[ $ALIAS ]] ; then
  ln -s $HOME/virtualenv/python$VERSION $HOME/virtualenv/python$ALIAS
fi

if [[ $PACKAGES ]] ; then
  $HOME/virtualenv/python$VERSION/bin/pip install --upgrade $PACKAGES
fi
